name: create manual docker image 
on:
  workflow_dispatch:
    inputs:   
      tag:
        required: true
      file_url:
        description: 'url (CURL compatible) of your custom openIMIS.json'
        required: false

jobs:
  publish-manual-docker-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Download custom openimis.json
      if: ${{ inputs.file_url != '' }}
      run: |
          curl -o ./openimis.json ${{ inputs.file_url }}
    - name: Build the openimis backend  Docker image
      run: |
         docker build . --tag ghcr.io/openimis/openimis-be:${{ github.event.inputs.tag }}
         docker push ghcr.io/openimis/openimis-be:${{ github.event.inputs.tag }}
